# Generated by Django 2.2.5 on 2019-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyInfo', '0002_auto_20191020_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbuilding',
            name='micro_district',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Микрорайон'),
        ),
    ]
