# Generated by Django 2.2.5 on 2019-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyInfo', '0003_auto_20191020_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbuilding',
            name='micro_district',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
