# Generated by Django 2.2.5 on 2019-10-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyInfo', '0005_auto_20191020_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbuilding',
            name='micro_district',
        ),
    ]
