# Generated by Django 2.2.5 on 2019-10-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyInfo', '0007_newbuilding_micro_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbuilding',
            name='micro_district',
        ),
    ]
