# Generated by Django 2.2.5 on 2019-10-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyInfo', '0009_newbuilding_micro_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbuilding',
            name='district',
            field=models.CharField(max_length=4),
        ),
    ]
